version: "3.7"
services:
  phpfpm:
    build:
      context: ./
      dockerfile: ./docker/phpfpm/Dockerfile.dev
    container_name: tdf_phpfpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: tdf_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8089:80
    depends_on:
      - phpfpm

  database:
    image: mysql:8.0
    container_name: tdf_database
    restart: unless-stopped
    volumes:
      - ./docker/database/data/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
