FROM php:8.3-fpm-alpine
WORKDIR /var/www/html/
# Adjust timezone to Tokyo - GMT+9
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
  echo "Asia/Tokyo" > /etc/timezone && apk del tzdata && rm -rf /var/cache/apk/*

# Build dependencies
RUN apk add --no-cache --virtual .build-deps supervisor linux-headers
# gd extension support
RUN apk add zlib-dev libpng-dev jpeg-dev  gd-dev jpeg-dev libjpeg-turbo-dev
# zip extension support
RUN apk add libzip-dev

RUN docker-php-ext-configure zip 
# Install PHP's extension
RUN docker-php-ext-install pdo_mysql gd zip

# Install Node.js and npm
RUN apk add --no-cache nodejs npm \
    && npm install -g npm@latest
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configuration files
COPY --chown=www-data:www-data ./docker/phpfpm/supervisor/conf.d/* /etc/supervisor/conf.d/
COPY --chown=www-data:www-data ./docker/phpfpm/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
COPY ./docker/phpfpm/docker-entrypoint.dev.sh /usr/bin/docker-entrypoint.dev.sh
COPY ./docker/phpfpm/php.ini /usr/local/etc/php/php.ini
COPY --chown=www-data:www-data . /var/www/html
RUN chmod -R 755 /var/www/html/storage

ENTRYPOINT ["/bin/sh", "/usr/bin/docker-entrypoint.dev.sh"]
